services:
  playwright:
    build: .
    container_name: wiki-language-tests
    env_file:
      - .env
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
    command: npx playwright test